### ISSUE TITLE
not joelang

### ISSUE THREAD

**Issue by vanility0001** [ian-ok/exity-pics#1]
Please fix.

**Comment by yourfriendoss** [comment]
Move it to joelang or unbased + unreal + ratio

**Comment by heheboi69** [comment]
pizza mogus @ian-ok

**Comment by environment-dev** [comment]
joelang is awful

**Comment by vanility0001** [comment]
Keep crying

**Comment by environment-dev** [comment]
i am not crying, i am simply stating the obvious

**Comment by vanility0001** [comment]
U have not even tried it

**Comment by ian-ok** [comment]
> pizza mogus @ian-ok

amongus
